### ISSUE TITLE
Implement a card to show the result of the most recent run

### ISSUE THREAD

**Issue by chappers00** [globallogicuki/globallogic-backstage-plugins#31]
This would allow you to put the latest Terraform Cloud run onto different tabs within Backstage.

For example this could be put on the Overview tab to show summarised Terraform status alongside other information there.

This card could include:

* Run result
* Executed by
* Resources added/removed/changes
* Duration

**Comment by ravinder-gill** [comment]
I am looking at this.

**Comment by himeshladva** [comment]
initially implemented by #43.

should make an enhancement and create a separate endpoint to fetch just the latest run from the backend api.

**Comment by himeshladva** [comment]
enhancement completed in #48
