### ISSUE TITLE
Add terraform plugins to Backstage community plugins page

### ISSUE THREAD

**Issue by himeshladva** [globallogicuki/globallogic-backstage-plugins#49]
In order to raise more awareness of the available plugins, we should be listed on the community plugins page.

More info on how this can be done here - https://backstage.io/docs/plugins/add-to-directory/.

**Comment by himeshladva** [comment]
https://github.com/backstage/backstage/pull/25669

**Comment by BillyMichael** [comment]
Thanks @himeshladva !

**Comment by himeshladva** [comment]
<img width="351" alt="image" src="https://github.com/user-attachments/assets/94634487-b6e2-4af6-8253-87c398840a7b">

completed!
